# Generated by Django 2.2.12 on 2020-11-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="voters",
            field=models.ManyToManyField(blank=True, to="backend.Citizen"),
        ),
    ]
