# Generated by Django 3.2.3 on 2021-08-26 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_auto_20201127_1438"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={"ordering": ["-starts_at"]},
        ),
    ]
