# Generated by Django 3.2.3 on 2021-11-10 11:42

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0003_alter_poll_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="polls/choices/"),
        ),
        migrations.AddField(
            model_name="poll",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "اختيار واحد"),
                    ("MULTI_CHOICE", "اختيارات متعددة"),
                ],
                default="MULTI_CHOICE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="choice",
            name="voters",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="poll",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("ends_at__gt", django.db.models.expressions.F("starts_at"))
                ),
                name="check_date",
            ),
        ),
    ]
