# Generated by Django 3.2.3 on 2022-08-05 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_add_live_results"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={"ordering": ["-created_at", "starts_at"]},
        ),
    ]
