# Generated by Django 3.2.3 on 2022-12-14 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Notification",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        ("body", models.TextField()),
                        ("is_read", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "subject_id",
                            models.PositiveIntegerField(blank=True, null=True),
                        ),
                        ("action_param", models.CharField(default="", max_length=255)),
                        (
                            "action_type",
                            models.CharField(
                                choices=[
                                    (
                                        "OPEN_SUBJECT",
                                        "Open Subject (comment, complaint, subject-access-request, dossier)",
                                    ),
                                    ("OPEN_URL", "Open url"),
                                ],
                                default="OPEN_SUBJECT",
                                max_length=30,
                            ),
                        ),
                        (
                            "subject_type",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="notifications",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "backend_notification",
                    },
                ),
            ],
            # You reference an existing table
            database_operations=[],
        )
    ]
