# Generated by Django 3.2.3 on 2022-12-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=[
                    (
                        "OPEN_SUBJECT",
                        "Open Subject (comment, complaint, subject-access-request, dossier)",
                    ),
                    ("OPEN_URL", "Open url"),
                    ("ETICKET_RESERVATION", "Digital Reservation"),
                ],
                default="OPEN_SUBJECT",
                max_length=30,
            ),
        ),
    ]
