# Generated by Django 3.2.3 on 2023-04-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0134_auto_20230326_0805'),
        ('notifications', '0003_alter_notification_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='municipality',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='notifications',
                to='backend.municipality',
            ),
        ),
    ]
