# Generated by Django 3.2.3 on 2023-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0004_notification_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
