# Generated by Django 2.2.17 on 2020-12-25 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backend", "0074_merge_20201209_0901"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSQueueElement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=8)),
                ("content", models.TextField()),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                            ("PENDING", "PENDING"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms",
                        to="backend.Municipality",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="smsqueueelement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("municipality__isnull", True), ("status", "PENDING"), _negated=True
                ),
                name="mun_null_implies_not_pending",
            ),
        ),
    ]
