# Generated by Django 3.2.3 on 2021-05-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsqueueelement",
            name="status",
            field=models.CharField(
                choices=[
                    ("SENT", "SENT"),
                    ("FAILED", "FAILED"),
                    ("PENDING", "PENDING"),
                    ("TOO_MANY_ATTEMPTS", "TOO_MANY_ATTEMPTS"),
                ],
                max_length=50,
            ),
        ),
    ]
