# Generated by Django 3.2.3 on 2022-12-04 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_url", models.CharField(help_text="API URL", max_length=1024)),
                ("body", models.TextField()),
                ("method", models.CharField(db_index=True, max_length=10)),
                ("client_ip", models.CharField(max_length=50)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        db_index=True, help_text="Response status code"
                    ),
                ),
                (
                    "execution_time",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="Server execution time (Not complete response time.)",
                        max_digits=8,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who made the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Log",
                "verbose_name_plural": "API Logs",
                "ordering": ("-timestamp",),
            },
        ),
    ]
