# Generated by Django 2.2.7 on 2020-01-21 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("matricule", models.CharField(max_length=200)),
                ("cin_number", models.TextField(max_length=8)),
                ("status", models.IntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("deposit_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("باجة", "باجة"),
                            ("أريانة", "أريانة"),
                            ("سيدي بوزيد", "سيدي بوزيد"),
                            ("منوبة", "منوبة"),
                            ("قفصة", "قفصة"),
                            ("المنستير", "المنستير"),
                            ("توزر", "توزر"),
                            ("جندوبة", "جندوبة"),
                            ("سوسة", "سوسة"),
                            ("تونس", "تونس"),
                            ("القصرين", "القصرين"),
                            ("قابس", "قابس"),
                            ("القيروان", "القيروان"),
                            ("سليانة", "سليانة"),
                            ("مدنين", "مدنين"),
                            ("بن عروس", "بن عروس"),
                            ("قبلي", "قبلي"),
                            ("صفاقس", "صفاقس"),
                            ("تطاوين", "تطاوين"),
                            ("نابل", "نابل"),
                            ("زغوان", "زغوان"),
                            ("الكاف", "الكاف"),
                            ("المهدية", "المهدية"),
                            ("بنزرت", "بنزرت"),
                        ],
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name_plural": "Municipalities",
            },
        ),
        migrations.CreateModel(
            name="SubjectAccessRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.CharField(max_length=200)),
                ("structure", models.CharField(max_length=200)),
                ("reference", models.CharField(blank=True, max_length=200, null=True)),
                ("form", models.CharField(max_length=200)),
                ("on_spot_document", models.BooleanField(default=False)),
                ("printed_document", models.BooleanField(default=False)),
                ("electronic_document", models.BooleanField(default=False)),
                ("parts_of_document", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "تم إستلام المطلب"),
                            ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                            ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                        ],
                        default="RECEIVED",
                        max_length=255,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Municipality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Committee",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Municipality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("os_version", models.CharField(max_length=40, null=True)),
                ("fcm_token", models.CharField(blank=True, max_length=200, null=True)),
                ("last_login", models.DateTimeField(auto_now=True, null=True)),
                (
                    "last_version",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("model", models.CharField(max_length=70, null=True)),
                ("product", models.CharField(max_length=70, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(choices=[("L", "Like")], max_length=10)),
                ("value", models.IntegerField()),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "backend"), ("model", "comment")),
                            models.Q(("app_label", "backend"), ("model", "news")),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "procedure",
                "verbose_name_plural": "procedures",
            },
        ),
        migrations.CreateModel(
            name="OperationUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField()),
                ("note", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "backend"), ("model", "complaint")),
                            models.Q(("app_label", "backend"), ("model", "dossier")),
                            models.Q(
                                ("app_label", "backend"),
                                ("model", "subjectaccessrequest"),
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Committee",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "news_object",
                "verbose_name_plural": "news",
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=9, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("service", models.IntegerField()),
                ("problem", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "تم إستلام المطلب"),
                            ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                            ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                        ],
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Municipality",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="committee",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.Municipality"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Committee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.Comment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cin_number", models.CharField(blank=True, max_length=8, null=True)),
                ("function", models.CharField(blank=True, max_length=30, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "facebook_account",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "municipalities",
                    models.ManyToManyField(
                        related_name="citizens", to="backend.Municipality"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "contact_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "president_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "president_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("jort_number", models.CharField(blank=True, max_length=30, null=True)),
                ("jort_date", models.DateField(blank=True, null=True)),
                (
                    "facebook_page",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("established_on", models.DateField(blank=True, null=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="complaint",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("address__isnull", False),
                    models.Q(_negated=True, address__exact=""),
                    models.Q(("longitude__isnull", False), ("latitude__isnull", False)),
                    _connector="OR",
                ),
                name="consistent_address",
            ),
        ),
    ]
