# Generated by Django 2.2.7 on 2020-01-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام المطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                ],
                default="RECEIVED",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام المطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                ],
                default="RECEIVED",
                max_length=255,
            ),
        ),
    ]
