# Generated by Django 2.2.7 on 2020-01-26 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_auto_20200126_0200"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="matricule",
        ),
        migrations.AddField(
            model_name="dossier",
            name="identifier",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
