# Generated by Django 2.2.7 on 2020-01-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_auto_20200127_0145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/associations_logos/"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/comments/"
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/complaints/"
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/municipalities/"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/news/"),
        ),
    ]
