# Generated by Django 2.2.7 on 2020-01-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_auto_20200127_0210"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectaccessrequest",
            name="form",
        ),
        migrations.AlterField(
            model_name="operationupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام المطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة المطلب"),
                ],
                default="RECEIVED",
                max_length=255,
            ),
        ),
    ]
