# Generated by Django 2.2.7 on 2020-01-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_auto_20200128_0118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="associations_logos/"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comments/"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="complaints/"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام الطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة الطلب"),
                    ("ACCEPTED", "تمت الموافقة على الطلب"),
                    ("REJECTED", "تعذر على البلدية الموافقة على الطلب"),
                ],
                default="RECEIVED",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام الطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة الطلب"),
                    ("ACCEPTED", "تمت الموافقة على الطلب"),
                    ("REJECTED", "تعذر على البلدية الموافقة على الطلب"),
                ],
                default="RECEIVED",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="municipalities/"),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news/"),
        ),
        migrations.AlterField(
            model_name="operationupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام الطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة الطلب"),
                    ("ACCEPTED", "تمت الموافقة على الطلب"),
                    ("REJECTED", "تعذر على البلدية الموافقة على الطلب"),
                ],
                default="RECEIVED",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subjectaccessrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام الطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة الطلب"),
                    ("ACCEPTED", "تمت الموافقة على الطلب"),
                    ("REJECTED", "تعذر على البلدية الموافقة على الطلب"),
                ],
                default="RECEIVED",
                max_length=255,
            ),
        ),
    ]
