# Generated by Django 2.2.7 on 2020-01-30 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_auto_20200130_0126"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="identifier",
        ),
        migrations.AddField(
            model_name="dossier",
            name="municipality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.Municipality",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dossier",
            name="unique_identifier",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dossier",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
