# Generated by Django 2.2.7 on 2020-02-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_auto_20200202_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="municipalities_logos/"
            ),
        ),
    ]
