# Generated by Django 2.2.7 on 2020-02-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_auto_20200205_0047"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "permissions": (
                    ("MANAGE_DOSSIERS", "Gerer les dossiers et demandes"),
                    ("MANAGE_PROCEDURES", "Gérer les procedures de la commune"),
                    ("MANAGE_COMPLAINTS", "Gérer les plaintes des citoyens"),
                    ("MANAGE_REPORTS", "Gerer les rapports du conseil municipal"),
                    (
                        "MANAGE_SUBJECT_ACCESS_REQUESTS",
                        "Gerer les demandes d'acces à l'information",
                    ),
                    ("MANAGE_COMMITTEES", "Gerer les comités du conseil municipal"),
                    ("MANAGE_NEWS", "Gerer les actualités de la commune"),
                    (
                        "MANAGE_PERMISSIONS",
                        "Gerer les permissions de chaque membre sur la plateforme",
                    ),
                ),
                "verbose_name_plural": "Municipalities",
            },
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="service",
        ),
        migrations.AddField(
            model_name="comment",
            name="municipality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.Municipality",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.Comment",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="type",
            field=models.CharField(
                choices=[
                    ("HEALTH_AND_HYGIENE", "النظافة و الصحة"),
                    ("ADMINISTRATION_AND_FINANCE", "الشؤون الإدارية و المالية"),
                    ("BUILDING_PERMITS", "التراخيص العمرانية"),
                    ("ROADWORKS_AND_LIGHTING", "أشغال الطريق والإنارة"),
                    ("OTHER", "أخرى"),
                ],
                default="OTHER",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
