# Generated by Django 2.2.7 on 2020-02-09 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.Committee",
            ),
        ),
    ]
