# Generated by Django 2.2.7 on 2020-02-10 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0015_auto_20200209_2134"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="followers",
            field=models.ManyToManyField(
                related_name="dossiers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
