# Generated by Django 2.2.7 on 2020-02-11 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_dossier_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="status",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="status",
        ),
        migrations.RemoveField(
            model_name="subjectaccessrequest",
            name="status",
        ),
    ]
