# Generated by Django 2.2.7 on 2020-02-17 00:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_auto_20200211_0115"),
    ]

    operations = [
        migrations.RenameField(
            model_name="procedure",
            old_name="order",
            new_name="display_order",
        ),
    ]
