# Generated by Django 2.2.7 on 2020-02-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_auto_20200217_0010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedures",
                to="backend.Municipality",
            ),
        ),
    ]
