# Generated by Django 2.2.7 on 2020-03-03 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_auto_20200217_0010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "comment")),
                    models.Q(("app_label", "backend"), ("model", "complaint")),
                    models.Q(("app_label", "backend"), ("model", "news")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="date",
            field=models.DateField(),
        ),
    ]
