# Generated by Django 2.2.7 on 2020-03-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0019_auto_20200303_0004"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "permissions": (
                    ("MANAGE_DOSSIERS", "Gerer les dossiers et demandes"),
                    ("MANAGE_PROCEDURES", "Gérer les procedures de la commune"),
                    ("MANAGE_COMPLAINTS", "Gérer les plaintes des citoyens"),
                    ("MANAGE_REPORTS", "Gerer les rapports du conseil municipal"),
                    (
                        "MANAGE_SUBJECT_ACCESS_REQUESTS",
                        "Gerer les demandes d'acces à l'information",
                    ),
                    ("MANAGE_COMMITTEES", "Gerer les comités du conseil municipal"),
                    ("MANAGE_NEWS", "Gerer les actualités de la commune"),
                    ("MANAGE_EVENTS", "Gerer les événements"),
                    (
                        "MANAGE_PERMISSIONS",
                        "Gerer les permissions de chaque membre sur la plateforme",
                    ),
                ),
                "verbose_name_plural": "Municipalities",
            },
        ),
        migrations.RemoveField(
            model_name="news",
            name="link",
        ),
        migrations.RemoveField(
            model_name="report",
            name="link",
        ),
        migrations.AddField(
            model_name="news",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="news/files/"),
        ),
        migrations.AddField(
            model_name="report",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="reports/files/"),
        ),
    ]
