# Generated by Django 2.2.7 on 2020-03-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_auto_20200304_0026"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectaccessrequest",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="subject-access-requests/files/"
            ),
        ),
    ]
