# Generated by Django 2.2.10 on 2020-03-04 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_subjectaccessrequest_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedures",
                to="backend.Municipality",
            ),
        ),
    ]
