# Generated by Django 2.2.10 on 2020-03-11 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0023_manager_municipality"),
        ("backend", "0019_auto_20200223_1052"),
    ]

    operations = []
