# Generated by Django 2.2.7 on 2020-03-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0023_manager_municipality"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticText",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
            ],
        ),
    ]
