# Generated by Django 2.2.10 on 2020-03-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_merge_20200311_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committees",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dossiers",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managers",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="subjectaccessrequest",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_access_requests",
                to="backend.Municipality",
            ),
        ),
    ]
