# Generated by Django 2.2.7 on 2020-03-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_statictext"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectaccessrequest",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
