# Generated by Django 2.2.7 on 2020-03-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0026_complaint_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="validation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
