# Generated by Django 2.2.7 on 2020-03-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0027_citizen_validation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
    ]
