# Generated by Django 2.2.7 on 2020-03-18 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0028_citizen_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="preferred_municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starred_citizens",
                to="backend.Municipality",
            ),
        ),
    ]
