# Generated by Django 2.2.7 on 2020-03-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0029_citizen_preferred_municipality"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="partner_municipalities",
            field=models.ManyToManyField(
                related_name="partner_associations", to="backend.Municipality"
            ),
        ),
    ]
