# Generated by Django 2.2.7 on 2020-03-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0030_association_partner_municipalities"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="procedures/files/"
            ),
        ),
    ]
