# Generated by Django 2.2.7 on 2020-03-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0031_procedure_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="type",
            field=models.CharField(
                choices=[
                    ("HEALTH_AND_HYGIENE", "النظافة و الصحة"),
                    ("ADMINISTRATION_AND_FINANCE", "الشؤون الإدارية و المالية"),
                    ("BUILDING_PERMITS", "التراخيص العمرانية"),
                    ("ROADWORKS_AND_LIGHTING", "أشغال الطريق والإنارة"),
                    ("OTHER", "أخرى"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
