# Generated by Django 2.2.10 on 2020-03-19 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0031_procedure_attachment"),
        ("backend", "0025_auto_20200318_1517"),
    ]

    operations = []
