# Generated by Django 2.2.10 on 2020-03-22 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0032_merge_20200319_0952"),
    ]

    operations = [
        migrations.AddField(
            model_name="registereddevice",
            name="device_unique_id",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="registereddevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
