# Generated by Django 2.2.7 on 2020-03-19 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0032_dossier_type"),
        ("backend", "0032_merge_20200319_0952"),
    ]

    operations = []
