# Generated by Django 2.2.7 on 2020-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0033_merge_20200319_2328"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="full_name_arabic",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
