# Generated by Django 2.2.7 on 2020-03-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0034_association_full_name_arabic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="partner_municipalities",
            field=models.ManyToManyField(
                blank=True,
                related_name="partner_associations",
                to="backend.Municipality",
            ),
        ),
    ]
