# Generated by Django 2.2.7 on 2020-03-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0035_auto_20200320_0002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="type",
            field=models.CharField(
                choices=[
                    ("BUILDING", "رخصة بناء"),
                    ("TEMPORARY_WORKS", "رخصة في الأشغال الوقتية"),
                    ("ONAS", "ربط بشبكة الشركة الوطنية للتطهير"),
                    ("SONEDE", "ربط بشبكة الشركة التونسية لتوزيع واستغلال المياه"),
                    ("OTHER", "أخرى"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
