# Generated by Django 2.2.10 on 2020-03-22 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0033_auto_20200322_1928"),
        ("backend", "0036_auto_20200321_0212"),
    ]

    operations = []
