# Generated by Django 2.2.7 on 2020-04-07 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0038_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="backend.Committee",
            ),
        ),
    ]
