# Generated by Django 2.2.7 on 2020-04-11 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0039_auto_20200407_0019"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="title",
        ),
    ]
