# Generated by Django 2.2.7 on 2020-04-15 00:35
from random import randint

from django.db import migrations


def populate_reference(apps, schema_editor):
    Dossier = apps.get_model("backend", "Dossier")
    for obj in Dossier.objects.all():
        if Dossier.objects.filter(unique_identifier=obj.unique_identifier).count() > 1:
            obj.unique_identifier = str(randint(1, 1000000000))
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0040_remove_complaint_title"),
    ]

    operations = [
        migrations.RunPython(populate_reference),
    ]
