# Generated by Django 2.2.7 on 2020-04-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0041_auto_20200415_0035"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="title",
        ),
        migrations.AlterField(
            model_name="dossier",
            name="unique_identifier",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
