# Generated by Django 2.2.10 on 2020-04-16 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0042_auto_20200415_0035"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaint",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="operationupdate",
            options={"ordering": ["-created_at"]},
        ),
    ]
