# Generated by Django 2.2.10 on 2020-04-19 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0043_auto_20200416_0101"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="note",
        ),
    ]
