# Generated by Django 2.2.7 on 2020-04-19 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0044_remove_dossier_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dossier",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "news_object",
                "verbose_name_plural": "news",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subjectaccessrequest",
            options={"ordering": ["-created_at"]},
        ),
    ]
