# Generated by Django 2.2.7 on 2020-04-19 15:58

from django.db import migrations


def remove_nullable_committee(apps, schema_editor):
    Report = apps.get_model("backend", "Report")
    Committee = apps.get_model("backend", "Committee")
    for obj in Report.objects.all():
        if obj.committee_id is None:
            obj.committee = Committee.objects.filter(
                municipality=obj.municipality
            ).first()
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0045_auto_20200419_1518"),
    ]

    operations = [
        migrations.RunPython(remove_nullable_committee),
    ]
