# Generated by Django 2.2.7 on 2020-04-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0046_auto_20200419_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="backend.Committee",
            ),
        ),
    ]
