# Generated by Django 2.2.7 on 2020-04-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0048_auto_20200419_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="registration_municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_time_citizens",
                to="backend.Municipality",
            ),
        ),
    ]
