# Generated by Django 2.2.10 on 2020-04-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0048_auto_20200419_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_param",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=[("open_subject", "open_subject")],
                default="open_subject",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="subject_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
    ]
