# Generated by Django 2.2.10 on 2020-04-21 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0049_citizen_registration_municipality"),
        ("backend", "0049_auto_20200421_1734"),
    ]

    operations = []
