# Generated by Django 2.2.7 on 2020-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0050_merge_20200421_1756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("OPEN_SUBJECT", "Open subject (comment, complaint...)"),
                    ("OPEN_URL", "Open url"),
                ],
                default="OPEN_SUBJECT",
                max_length=30,
            ),
        ),
    ]
