# Generated by Django 2.2.7 on 2020-04-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0051_auto_20200422_2050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="subject_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
