# Generated by Django 2.2.7 on 2020-04-22 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0053_auto_20200422_2302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="preferred_municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starred_citizens",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="registration_municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_time_citizens",
                to="backend.Municipality",
            ),
        ),
    ]
