# Generated by Django 2.2.10 on 2020-05-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0054_auto_20200422_2306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="function",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
