# Generated by Django 2.2.10 on 2020-05-06 14:25

from django.db import migrations


class ComplaintTypes:
    HEALTH_AND_HYGIENE = "HEALTH_AND_HYGIENE"
    ADMINISTRATION_AND_FINANCE = "ADMINISTRATION_AND_FINANCE"
    BUILDING_PERMITS = "BUILDING_PERMITS"
    ROADWORKS_AND_LIGHTING = "ROADWORKS_AND_LIGHTING"
    OTHER = "OTHER"

    @staticmethod
    def get_choices():
        return (
            (ComplaintTypes.HEALTH_AND_HYGIENE, "النظافة و الصحة"),
            (ComplaintTypes.ADMINISTRATION_AND_FINANCE, "الشؤون الإدارية و المالية"),
            (ComplaintTypes.BUILDING_PERMITS, "التراخيص العمرانية"),
            (ComplaintTypes.ROADWORKS_AND_LIGHTING, "أشغال الطريق والإنارة"),
            (ComplaintTypes.OTHER, "أخرى"),
        )


COMPLAINT_TYPE_DICT = dict(ComplaintTypes.get_choices())


def transfer_complaint_types(apps, schema_editor):
    Complaint = apps.get_model("backend", "Complaint")
    Municipality = apps.get_model("backend", "Municipality")

    for municipality in Municipality.objects.all().filter(is_active=True):
        for category_name in dict(ComplaintTypes.get_choices()).values():
            municipality.categories.create(name=category_name)

    for complaint in Complaint.objects.all():
        if not complaint.municipality.is_active:
            continue
        complaint_type_name = COMPLAINT_TYPE_DICT.get(complaint.type, "أخرى")
        category = complaint.municipality.categories.get(name=complaint_type_name)
        complaint.category = category
        complaint.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0056_auto_20200506_1416"),
    ]

    operations = [
        migrations.RunPython(transfer_complaint_types),
    ]
