# Generated by Django 2.2.10 on 2020-05-06 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0057_auto_20200506_1425"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="type",
        ),
    ]
