# Generated by Django 2.2.10 on 2020-05-13 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0055_auto_20200507_1233"),
        ("backend", "0058_remove_complaint_type"),
    ]

    operations = []
