# Generated by Django 2.2.10 on 2020-05-13 23:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0059_merge_20200513_0002"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="complaintcategory",
            unique_together={("municipality", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="complaintsubcategory",
            unique_together={("municipality", "name", "category")},
        ),
    ]
