# Generated by Django 2.2.12 on 2020-05-23 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0060_auto_20200513_2340"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="complaintsubcategory",
            unique_together={("name", "category")},
        ),
        migrations.RemoveField(
            model_name="complaintsubcategory",
            name="municipality",
        ),
    ]
