# Generated by Django 2.2.12 on 2020-05-26 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0061_auto_20200523_1756"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaintcategory",
            options={"verbose_name_plural": "complaint categories"},
        ),
        migrations.AlterModelOptions(
            name="complaintsubcategory",
            options={"verbose_name_plural": "complaint subcategories"},
        ),
    ]
