# Generated by Django 2.2.12 on 2020-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0062_auto_20200526_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="latitude",
            field=models.DecimalField(
                decimal_places=7, default=36.797423, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="longitude",
            field=models.DecimalField(
                decimal_places=7, default=10.165894, max_digits=10
            ),
        ),
    ]
