# Generated by Django 2.2.12 on 2020-06-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0063_auto_20200606_0813"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
