# Generated by Django 2.2.12 on 2020-11-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0066_municipality_facebook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="type",
            field=models.CharField(
                choices=[
                    ("خدمات إدارية", "خدمات إدارية"),
                    ("خدمات الحالة المدنية", "خدمات الحالة المدنية"),
                    ("خدمات عمرانية", "خدمات عمرانية"),
                    ("خدمات ترتيبية", "خدمات ترتيبية"),
                    ("خدمات مالية", "خدمات مالية"),
                    ("خدمات مختلفة", "خدمات مختلفة"),
                ],
                default="خدمات مختلفة",
                max_length=50,
            ),
        ),
    ]
