# Generated by Django 2.2.12 on 2020-11-18 15:58

from django.db import migrations, models
from django.utils.timezone import timedelta


class Migration(migrations.Migration):
    replaces = [
        ("backend", "0067_news_to_broadcast"),
        ("backend", "0068_auto_20201117_2006"),
        ("backend", "0069_auto_20201117_2033"),
    ]

    dependencies = [
        ("backend", "0066_municipality_facebook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="to_broadcast",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="municipality",
            name="broadcast_frquency",
            field=models.DurationField(default=timedelta(7)),
        ),
        migrations.AddField(
            model_name="municipality",
            name="last_broadcast",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
