# Generated by Django 2.2.12 on 2020-11-27 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0067_news_to_broadcast_squashed_0069_auto_20201117_2033"),
        ("backend", "0067_procedure_type"),
    ]

    operations = []
