# Generated by Django 2.2.12 on 2020-11-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0068_merge_20201127_1437"),
    ]

    operations = [
        migrations.RenameField(
            model_name="municipality",
            old_name="broadcast_frquency",
            new_name="broadcast_frequency",
        ),
        migrations.AlterField(
            model_name="municipality",
            name="last_broadcast",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
