# Generated by Django 2.2.12 on 2020-12-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0069_auto_20201127_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="sms_credit",
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name="municipality",
            name="total_sms_consumption",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SMSBroadcastRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("SENDING", "SENDING"),
                            ("SENT", "SENT"),
                            ("DECLINED", "DECLINED"),
                        ],
                        default="PENDING",
                        max_length=255,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("REGISTERED_CITIZENS", "REGISTERED_CITIZENS"),
                            ("FOLLOWING_CITIZENS", "FOLLOWING_CITIZENS"),
                        ],
                        max_length=255,
                    ),
                ),
                ("text", models.CharField(max_length=160)),
                ("scheduled_on", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_broadcast_requests",
                        to="backend.Manager",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_broadcast_requests",
                        to="backend.Municipality",
                    ),
                ),
            ],
        ),
    ]
