# Generated by Django 2.2.12 on 2020-12-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0069_auto_20201127_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile-pictures"
            ),
        ),
    ]
