# Generated by Django 2.2.17 on 2020-12-06 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0070_citizen_profile_picture"),
        ("backend", "0070_auto_20201203_1301"),
    ]

    operations = []
