# Generated by Django 2.2.17 on 2020-12-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0071_merge_20201206_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
    ]
