# Generated by Django 2.2.17 on 2020-12-08 18:20

from django.db import migrations

import backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0072_auto_20201207_1139"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("posts", backend.models.PostManager()),
                ("comments", backend.models.CommentManager()),
            ],
        ),
    ]
