# Generated by Django 2.2.12 on 2020-12-09 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0071_auto_20201206_1302"),
        ("backend", "0073_auto_20201208_1920"),
    ]

    operations = []
