# Generated by Django 2.2.17 on 2020-12-26 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0074_merge_20201209_0901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="all_comments",
                to="backend.Committee",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_comments",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.Committee",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.Committee",
            ),
        ),
    ]
