# Generated by Django 2.2.12 on 2020-12-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0074_merge_20201209_0901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsbroadcastrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_broadcast_requests",
                to="backend.Manager",
            ),
        ),
        migrations.AlterField(
            model_name="smsbroadcastrequest",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_broadcast_requests",
                to="backend.Municipality",
            ),
        ),
        migrations.AlterField(
            model_name="smsbroadcastrequest",
            name="target",
            field=models.CharField(
                choices=[
                    ("REGISTERED_CITIZENS", "REGISTERED_CITIZENS"),
                    ("FOLLOWING_CITIZENS", "FOLLOWING_CITIZENS"),
                    ("ALL_CITIZENS", "ALL_CITIZENS"),
                    ("CUSTOM", "CUSTOM"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="SMSBroadCastPhoneNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=8)),
                (
                    "sms_broadcast_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="backend.SMSBroadcastRequest",
                    ),
                ),
            ],
        ),
    ]
