# Generated by Django 2.2.17 on 2021-01-04 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0075_auto_20201221_1134"),
        ("backend", "0075_auto_20201226_1251"),
    ]

    operations = []
