# Generated by Django 2.2.17 on 2021-01-22 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0077_hit"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.CharField(
                choices=[
                    ("بلاغ", "بلاغ"),
                    ("أنشطة وتظاهرات", "أنشطة وتظاهرات"),
                    ("أشغال و صيانة", "أشغال و صيانة"),
                    ("طلب عروض", "طلب عروض"),
                    ("عروض شغل", "عروض شغل"),
                ],
                default="بلاغ",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="backend.News",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="news", to="backend.NewsTag"
            ),
        ),
    ]
