# Generated by Django 2.2.17 on 2021-01-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0078_auto_20210122_1123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="registration_municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_citizens",
                to="backend.Municipality",
            ),
        ),
    ]
