# Generated by Django 2.2.17 on 2021-01-24 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0079_auto_20210123_2145"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="committee",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="starting_date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="time",
            new_name="starting_time",
        ),
        migrations.AddField(
            model_name="event",
            name="committees",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="backend.Committee"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="ending_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="ending_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="backend.Citizen"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
