# Generated by Django 2.2.17 on 2021-02-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0080_auto_20210124_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="name_fr",
            field=models.CharField(default="mun", max_length=255),
            preserve_default=False,
        ),
    ]
