# Generated by Django 2.2.17 on 2021-02-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0082_auto_20210205_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="interested_citizen",
            field=models.ManyToManyField(
                blank=True, related_name="events_interested_in", to="backend.Citizen"
            ),
        ),
    ]
