# Generated by Django 2.2.17 on 2021-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0083_event_interested_citizen"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="is_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="ending_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="starting_time",
            field=models.TimeField(null=True),
        ),
    ]
