# Generated by Django 2.2.17 on 2021-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0085_auto_20210307_1159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ending_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="ending_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="starting_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
