# Generated by Django 2.2.12 on 2021-04-14 20:38

import django.db.models.manager
from django.db import migrations

import backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0088_auto_20210317_2244"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("posts", backend.models.PostManager()),
                ("comments", backend.models.CommentManager()),
            ],
        ),
    ]
