# Generated by Django 2.2.17 on 2021-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0089_auto_20210414_2038"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="phone_number",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
