# Generated by Django 2.2.17 on 2021-04-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0090_dossier_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.Region",
            ),
        ),
    ]
