# Generated by Django 2.2.12 on 2021-04-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0091_auto_20210420_2259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="type",
            field=models.CharField(
                choices=[
                    ("BUILDING", "رخصة بناء"),
                    ("TEMPORARY_WORKS", "رخصة في الأشغال الوقتية"),
                    ("TAKSIM", "رخصة المصادقة على تقسيم"),
                    ("STREET", "رخصة الاستغلال الوقتي للطريق العام"),
                    ("SONEDE", "ربط بشبكة المياه"),
                    ("ONAS", "ربط بشبكة التطهير"),
                    ("ELECTRICITY", "ربط بشبكة الكهرباء"),
                    ("GAZ", "ربط بشبكة الغاز"),
                    ("OTHER", "غير محدد"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
