# Generated by Django 2.2.17 on 2021-05-03 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0092_auto_20210428_0007"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created_at"]},
        ),
    ]
