# Generated by Django 2.2.17 on 2021-05-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0094_auto_20210503_1440"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationupdate",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "complaint")),
                    models.Q(("app_label", "backend"), ("model", "dossier")),
                    models.Q(
                        ("app_label", "backend"), ("model", "subjectaccessrequest")
                    ),
                    models.Q(("app_label", "backend"), ("model", "comment")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
    ]
