# Generated by Django 3.2.3 on 2021-05-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("backend", "0095_auto_20210512_1957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationupdate",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "complaint")),
                    models.Q(("app_label", "backend"), ("model", "dossier")),
                    models.Q(
                        ("app_label", "backend"), ("model", "subjectaccessrequest")
                    ),
                    models.Q(("app_label", "backend"), ("model", "comment")),
                    models.Q(("app_label", "backend"), ("model", "reservation")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
