# Generated by Django 3.2.3 on 2021-05-22 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0096_alter_operationupdate_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("QUESTION", "سؤال"), ("SUGGESTION", "مقترح")],
                default="SUGGESTION",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVATED", "مفتوح"),
                            ("ARCHIVED", "مغلق"),
                            ("HIDDEN", "مخفي"),
                        ],
                        default="HIDDEN",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="backend.municipality",
                    ),
                ),
            ],
            options={
                "unique_together": {("municipality", "label")},
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.topic",
            ),
        ),
    ]
