# Generated by Django 3.2.3 on 2021-06-01 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0097_add_topic_to_comment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="complaintcategory",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="complaintcategory",
            name="municipality",
        ),
    ]
