# Generated by Django 3.2.3 on 2021-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0098_auto_20210601_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
