# Generated by Django 3.2.3 on 2021-06-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0099_alter_municipality_facebook_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QUESTION", "سؤال"),
                    ("SUGGESTION", "مقترح"),
                    ("REMARK", "ملاحظة"),
                ],
                default="SUGGESTION",
                max_length=50,
                null=True,
            ),
        ),
    ]
