# Generated by Django 3.2.3 on 2021-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0100_alter_comment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام الطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة الطلب"),
                    ("ACCEPTED", "تمت الموافقة على الطلب"),
                    ("REJECTED", "تعذر على البلدية الموافقة على الطلب"),
                    ("NOT_CLEAR", "المطلب منقوص أو غير مفهوم"),
                    ("INVALID", "الوثيقة المطلوبة ليست من مشمولات البلدية"),
                ],
                default="RECEIVED",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_state_citizen",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "تم إستلام الطلب"),
                    ("PROCESSING", "بصدد \xa0معالجة الطلب"),
                    ("ACCEPTED", "تمت الموافقة على الطلب"),
                    ("REJECTED", "تعذر على البلدية الموافقة على الطلب"),
                    ("NOT_CLEAR", "المطلب منقوص أو غير مفهوم"),
                    ("INVALID", "الوثيقة المطلوبة ليست من مشمولات البلدية"),
                ],
                default="ACCEPTED",
                max_length=255,
            ),
        ),
    ]
