# Generated by Django 3.2.3 on 2021-07-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0102_operationupdate_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "ذكر"), ("FEMALE", "أنثى")],
                default="MALE",
                max_length=40,
            ),
        ),
    ]
