# Generated by Django 3.2.3 on 2021-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0103_add_gender_for_citizen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "ذكر"), ("FEMALE", "أنثى")],
                max_length=40,
                null=True,
            ),
        ),
    ]
