# Generated by Django 3.2.3 on 2021-08-08 11:04

from django.db import migrations


def nullify_citizen_gender(apps, schema_editor):
    Citizen = apps.get_model("backend", "Citizen")
    for citizen in Citizen.objects.all():
        citizen.gender = None
        citizen.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0104_alter_citizen_gender"),
    ]

    operations = [
        migrations.RunPython(nullify_citizen_gender),
    ]
