# Generated by Django 3.2.3 on 2021-09-05 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0105_auto_20210808_1104"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["-created_at"]},
        ),
    ]
