# Generated by Django 3.2.3 on 2021-09-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0106_alter_topic_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="has_eticket",
            field=models.BooleanField(default=False),
        ),
    ]
