# Generated by Django 3.2.3 on 2021-09-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0107_add_eticket_field_in_municipality"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="complaint_categories",
            field=models.ManyToManyField(
                related_name="managers", to="backend.ComplaintCategory"
            ),
        ),
    ]
