# Generated by Django 3.2.3 on 2021-10-06 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0108_manager_complaint_categories"),
        ("backend", "0109_add_forum_permission"),
    ]

    operations = []
