# Generated by Django 3.2.3 on 2021-10-19 14:14

from django.db import migrations

import backend.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0111_auto_20211006_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="service_complaints",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="service_dossiers",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="service_eticket",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="DEACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="service_events",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="service_forum",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="service_news",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="service_procedures",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="service_reports",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="service_sar",
            field=backend.models.StatusCharField(
                choices=[
                    ("DEACTIVATED", "غير مفعل"),
                    ("IN_PROGRESS", "التفعيل جري"),
                    ("ACTIVATED", "مفعل"),
                ],
                default="ACTIVATED",
                max_length=20,
            ),
        ),
    ]
