# Generated by Django 3.2.3 on 2021-10-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0111_auto_20211006_1644"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereddevice",
            name="device_unique_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
