# Generated by Django 3.2.3 on 2021-10-23 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0112_add_municipality_features"),
        ("backend", "0112_alter_registereddevice_device_unique_id"),
    ]

    operations = []
