# Generated by Django 3.2.3 on 2021-11-01 18:18

from django.db import migrations


def patch_operation_updates_comments(apps, schema_editor):
    Comment = apps.get_model("backend", "Comment")
    OperationUpdate = apps.get_model("backend", "OperationUpdate")
    ContentType = apps.get_model("contenttypes", "ContentType")
    comment_content_type = ContentType.objects.get_for_model(Comment)
    for comment in Comment.objects.all():
        ops = OperationUpdate.objects.filter(
            content_type=comment_content_type, object_id=comment.pk
        )
        if not ops.exists():
            update = OperationUpdate.objects.create(
                status="RECEIVED",
                content_type=comment_content_type,
                object_id=comment.pk,
            )
            update.created_at = comment.created_at
            update.save()


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0113_merge_20211023_1347"),
    ]

    operations = [
        migrations.RunPython(patch_operation_updates_comments),
    ]
