# Generated by Django 3.2.3 on 2021-12-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0114_auto_20211101_1818"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="unique_identifier",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="dossier",
            constraint=models.UniqueConstraint(
                fields=("unique_identifier", "municipality"),
                name="unique_per_municipality",
            ),
        ),
    ]
