# Generated by Django 3.2.3 on 2022-02-13 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0115_fix_unique_dossier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "ordering": ["-is_active", "-is_signed"],
                "permissions": (
                    ("MANAGE_DOSSIERS", "Gerer les dossiers et demandes"),
                    ("MANAGE_PROCEDURES", "Gérer les procedures de la commune"),
                    ("MANAGE_COMPLAINTS", "Gérer les plaintes des citoyens"),
                    ("MANAGE_REPORTS", "Gerer les rapports du conseil municipal"),
                    (
                        "MANAGE_SUBJECT_ACCESS_REQUESTS",
                        "Gerer les demandes d'acces à l'information",
                    ),
                    ("MANAGE_COMMITTEES", "Gerer les comités du conseil municipal"),
                    ("MANAGE_NEWS", "Gerer les actualités de la commune"),
                    ("MANAGE_EVENTS", "Gerer les événements"),
                    (
                        "MANAGE_PERMISSIONS",
                        "Gerer les permissions de chaque membre sur la plateforme",
                    ),
                    ("MANAGE_APPOINTMENTS", "Gerer les rendez-vous"),
                    ("MANAGE_FORUM", "Gerer le forum"),
                    ("MANAGE_POLLS", "Gerer les sondages"),
                ),
                "verbose_name_plural": "Municipalities",
            },
        ),
    ]
