# Generated by Django 3.2.3 on 2022-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0116_add_manage_polls_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereddevice",
            name="device_unique_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
