# Generated by Django 3.2.3 on 2022-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0117_alter_registereddevice_device_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="population",
            field=models.IntegerField(default=0),
        ),
    ]
