# Generated by Django 3.2.3 on 2022-09-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0118_municipality_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="see_broadcast_forms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="citizen",
            name="see_ambassadors_forms",
            field=models.BooleanField(default=False),
        ),
    ]
