# Generated by Django 3.2.9 on 2022-10-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0122_alter_municipality_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
