# Generated by Django 3.2.3 on 2022-10-19 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0123_building_dossierattachment"),
        ("backend", "0123_citizen_is_deleted"),
    ]

    operations = []
