# Generated by Django 3.2.9 on 2022-10-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0124_merge_20221019_2242"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
