# Generated by Django 3.2.3 on 2022-11-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0125_manager_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationupdate",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="operation-updates"
            ),
        ),
    ]
