# Generated by Django 3.2.3 on 2022-11-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0126_operationupdate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsbroadcastrequest",
            name="target",
            field=models.CharField(
                choices=[
                    ("REGISTERED_CITIZENS", "REGISTERED_CITIZENS"),
                    ("FOLLOWING_CITIZENS", "FOLLOWING_CITIZENS"),
                    ("ALL_CITIZENS", "ALL_CITIZENS"),
                    ("CUSTOM", "CUSTOM"),
                    ("INACTIVE_CITIZENS", "INACTIVE_CITIZENS"),
                ],
                max_length=255,
            ),
        ),
    ]
