# Generated by Django 3.2.3 on 2022-11-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0127_alter_smsbroadcastrequest_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsbroadcastrequest",
            name="number_of_days",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
