# Generated by Django 3.2.3 on 2022-12-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0129_municipality_contract_signing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationupdate",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="operation-updates"
            ),
        ),
    ]
