# Generated by Django 3.2.3 on 2022-12-14 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0130_alter_operationupdate_image"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Notification",
                ),
            ],
            # You want to reuse the table, so don't drop it
            database_operations=[],
        )
    ]
