# Generated by Django 3.2.3 on 2023-03-26 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0132_alter_municipality_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="followers",
            field=models.ManyToManyField(
                related_name="comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="followers",
            field=models.ManyToManyField(
                related_name="complaints", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subjectaccessrequest",
            name="followers",
            field=models.ManyToManyField(
                related_name="subject_access_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
