# Generated by Django 3.2.3 on 2023-03-26 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0133_auto_20230326_0759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="complaints", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="subjectaccessrequest",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subject_access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
