# Generated by Django 3.2.3 on 2022-09-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etickets_v2", "0001_initial"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="reservation",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[],
        )
    ]
