# Generated by Django 3.2.3 on 2022-11-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etickets_v2", "0002_reservation_is_active"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="reservation",
                    name="is_physical",
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[],
        )
    ]
