# Generated by Django 3.2.3 on 2022-12-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etickets_v2", "0003_reservation_is_physical"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="reservation",
                    name="service",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="etickets_v2.service",
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
