# Generated by Django 3.2.8 on 2022-12-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etickets_v2", "0005_alter_service_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="avg_time_per_person",
            field=models.IntegerField(default=8),
        ),
    ]
