# Generated by Django 3.2.3 on 2022-12-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etickets_v2", "0006_service_avg_time_per_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="local_ip",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
