# Generated by Django 3.2.8 on 2022-12-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etickets_v2", "0007_alter_agency_local_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
