# Generated by Django 3.2.3 on 2023-03-03 19:38

import django.db.models.manager
from django.db import migrations

import etickets_v2.models


class Migration(migrations.Migration):
    dependencies = [
        ("etickets_v2", "0008_alter_agency_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="reservation",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "no_longer_valid_objects",
                    etickets_v2.models.NoLongerValidReservationManager(),
                ),
            ],
        ),
    ]
