# Generated by Django 3.2.3 on 2023-03-29 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('etickets_v2', '0009_alter_reservation_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'agency',
                'verbose_name_plural': 'agencies',
            },
        ),
    ]
