# Generated by Django 3.2.3 on 2023-03-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('etickets_v2', '0010_alter_agency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='agency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='services',
                to='etickets_v2.agency',
            ),
        ),
    ]
