# Generated by Django 3.2.3 on 2023-04-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('etickets_v2', '0011_alter_service_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='secured_connection',
            field=models.BooleanField(default=False),
        ),
    ]
