# Generated by Django 3.2.3 on 2023-04-07 22:43

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import etickets_v2.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etickets_v2', '0012_agency_secured_connection'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('valid_objects', etickets_v2.models.ValidReservationManager()),
                (
                    'no_longer_valid_objects',
                    etickets_v2.models.NoLongerValidReservationManager(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='etickets_v2_reservations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
