# Generated by Django 3.2.3 on 2023-04-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('etickets_v2', '0013_auto_20230407_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='current_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
