# Generated by Django 3.2.3 on 2022-10-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationupdateperformance",
            name="accepted_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operationupdateperformance",
            name="average_first_response_days",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operationupdateperformance",
            name="invalid_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operationupdateperformance",
            name="not_clear_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operationupdateperformance",
            name="processing_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operationupdateperformance",
            name="received_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="operationupdateperformance",
            name="rejected_percentage",
            field=models.FloatField(default=0),
        ),
    ]
