# Generated by Django 3.2.3 on 2022-10-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_auto_20221003_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationupdateperformance",
            name="average_first_response_days",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
