# Generated by Django 3.2.3 on 2022-12-12 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etickets_v2", "0004_alter_reservation_service"),
        ("stats", "0003_alter_operationupdateperformance_average_first_response_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="EticketsPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("physical_reservation_percentage", models.FloatField(default=0)),
                ("digital_reservation_percentage", models.FloatField(default=0)),
                ("not_digitized_reservation_percentage", models.FloatField(default=0)),
                ("push_notifications_sent", models.FloatField(default=0)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etickets_performance",
                        to="etickets_v2.agency",
                    ),
                ),
            ],
        ),
    ]
