# Generated by Django 3.2.3 on 2021-09-18 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backend", "0107_add_eticket_field_in_municipality"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("base_url", models.URLField()),
                ("authentication_user", models.CharField(max_length=50)),
                ("authentication_password", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("num_agency", models.CharField(max_length=150)),
                ("weekday_first_start", models.TimeField()),
                ("weekday_first_end", models.TimeField()),
                ("weekday_second_start", models.TimeField()),
                ("weekday_second_end", models.TimeField()),
                ("saturday_first_start", models.TimeField(blank=True, null=True)),
                ("saturday_first_end", models.TimeField(blank=True, null=True)),
                ("saturday_second_start", models.TimeField(blank=True, null=True)),
                ("saturday_second_end", models.TimeField(blank=True, null=True)),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agencies",
                        to="backend.municipality",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agencies",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=150)),
                ("service_id", models.IntegerField()),
                ("ticket_info", models.TextField(blank=True, null=True)),
                ("ticket_num", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="etickets.agency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
